=== NBCharro/DAW/LenguajeDeMarcas/blanco_charro_nelson_LMSGI04_Tarea/ejercicio2/blanco_charro_nelson_torneo.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT torneo(participante+)>
<!ATTLIST torneo edicion CDATA #REQUIRED>
<!ATTLIST torneo anteriorGanador CDATA #REQUIRED>

<!ELEMENT participante(nombre, edad, pais, cabezaDeSerie?)>
<!ATTLIST participante codigo ID #REQUIRED>
<!ATTLIST participante compaÃ±ero CDATA #REQUIRED>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT cabezaDeSerie EMPTY>

=== NBCharro/DAW/LenguajeDeMarcas/blanco_charro_nelson_LMSGI04_Tarea/ejercicio2/xml_prueba/novalidos/torneo2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE torneo SYSTEM "blanco_charro_nelson_torneo.dtd">

<torneo edicion="2001" anteriorGanador="D32">
  <participante codigo="D12" compañero="D42">
    <nombre>Ignacio</nombre>
    <edad>48</edad>
    <pais>Brasil</pais>
  </participante>

  <participante codigo="D12" compañero="D32">
    <nombre>Sofia</nombre>  
    <edad>81</edad>
    <pais>España</pais>
  </participante>

  <participante codigo="D32" compañero="D22">
    <nombre>Vanesa</nombre>
    <edad>67</edad>
    <pais>Portugal</pais>
    <cabezaDeSerie/>
  </participante>

  <participante codigo="D42" compañero="D12">
    <nombre>Belinda</nombre>  
    <edad>65</edad>
    <pais>Francia</pais>
  </participante>

</torneo>
